// <auto-generated>

namespace Foxy.FewTorches {
  [Verse.StaticConstructorOnStartup]
  internal static class Static {
    static Static() {
      Logger.Log("Applying patches...");
      new HarmonyLib.Harmony("Foxy.FewTorches").PatchAll();
      Logger.Log("Patches applied.");
    }
  }
}